Update cd.yml

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -97,8 +97,8 @@ jobs:
       - name: Connect and Deploy Docker Containers on EC2
         env:
           PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
-          REPOSITORYBACK: "${{ secrets.DOCKER_USERNAME }}/cs360_test_backend"
-          REPOSITORYFRONT: "${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend"
+          REPOSITORYBACK: "${{ secrets.DOCKER_USERNAME }}/foodadvisor-api"
+          REPOSITORYFRONT: "${{ secrets.DOCKER_USERNAME }}/foodadviro-client"
         run: |
           # Save the private key from the secret to a file
           echo "$PRIVATE_KEY" > private_key.pem
@@ -129,34 +129,34 @@ jobs:
           sudo systemctl restart docker
 
           # Pull and run the backend container
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_backend:latest
-          sudo docker run --name cs360_test_backend \
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foodadvisor-api:latest
+          sudo docker run --name foodadvisor-api \
             -p 1337:1337 \
             -e HOST=0.0.0.0 \
             -e PORT=1337 \
             -e STRAPI_ADMIN_CLIENT_URL=http://${{ env.INSTANCE_PUBLIC_IPV4 }}:3000/ \
             -e STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=ARNFCb9zrC9ZHm5hZzCigWivD40icS4s \
             -v /path/on/host/uploads:/app/public/uploads \
-            -d ${{ secrets.DOCKER_USERNAME }}/cs360_test_backend:latest || { echo "Failed to run backend container"; exit 1; }
+            -d ${{ secrets.DOCKER_USERNAME }}/foodadvisor-api:latest || { echo "Failed to run backend container"; exit 1; }
             
           
           # ตรวจสอบสถานะของ backend container
           echo "Checking Backend Container Status..."
-          BACKEND_STATUS=$(sudo docker inspect -f '{{.State.Status}}' cs360_test_backend)
+          BACKEND_STATUS=$(sudo docker inspect -f '{{.State.Status}}' foodadvisor-api)
           if [ "$BACKEND_STATUS" != "running" ]; then
             echo "Backend container failed to start. Check logs for details."
-            sudo docker logs cs360_test_backend
+            sudo docker logs foodadvisor-api
             exit 1
           fi
           echo "Backend deployed successfully."
           
           # Pull และ run frontend container
           echo "Deploying Frontend Container..."
-          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend:latest
-          sudo docker run --name cs360_test_frontend \
+          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/foodadvisor-client:latest
+          sudo docker run --name foodadvisor-client \
             -p 3000:3000 \
             -e NEXT_PUBLIC_API_URL=http://${{ env.INSTANCE_PUBLIC_IPV4 }}:1337/ \
             -e PREVIEW_SECRET=ARNFCb9zrC9ZHm5hZzCigWivD40icS4s \
-            -d ${{ secrets.DOCKER_USERNAME }}/cs360_test_frontend:latest /bin/bash -c "npm install && npm run build && npm start"
+            -d ${{ secrets.DOCKER_USERNAME }}/foodadvisor-client:latest /bin/bash -c "npm install && npm run build && npm start"
           
           EOF
