Update cd2.yml

diff --git a/.github/workflows/cd2.yml b/.github/workflows/cd2.yml
--- a/.github/workflows/cd2.yml
+++ b/.github/workflows/cd2.yml
@@ -12,7 +12,7 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3    
 
-      # Step 2: Check if Docker Image Exists
+      # Step 2: Check if Docker Image Exists for API
       - name: Check if Docker Image Exists API
         id: check_image_API
         run: |
@@ -24,7 +24,8 @@ jobs:
               exit 1
           fi
           echo "Docker image exists. Proceeding to deployment."
-
+      
+      # Step 3: Check if Docker Image Exists for Client
       - name: Check if Docker Image Exists Client
         id: check_image_client
         run: |
@@ -66,8 +67,10 @@ jobs:
 
           echo "Instance ID: $INSTANCE_ID"
 
+          # Wait for EC2-Instance to be running
           aws ec2 wait instance-running --instance-ids $INSTANCE_ID
 
+          # Output the instance public DNS
           INSTANCE_PUBLIC_DNS=$(aws ec2 describe-instances \
             --instance-ids $INSTANCE_ID \
             --query 'Reservations[0].Instances[0].PublicDnsName' \
@@ -75,6 +78,7 @@ jobs:
           echo "Instance Public DNS: $INSTANCE_PUBLIC_DNS"
           echo "INSTANCE_PUBLIC_DNS=$INSTANCE_PUBLIC_DNS" >> $GITHUB_ENV
 
+          # Output the instance public IPv4
           INSTANCE_PUBLIC_IPV4=$(aws ec2 describe-instances \
             --instance-ids $INSTANCE_ID \
             --query 'Reservations[0].Instances[0].PublicIpAddress' \
@@ -83,7 +87,7 @@ jobs:
           echo "INSTANCE_PUBLIC_IPV4=$INSTANCE_PUBLIC_IPV4" >> $GITHUB_ENV
           sleep 5
 
-      # Step 5: Deploying the Web Application to EC2
+      # Step 6: Connect to EC2 Instance and Deploy API & CLIENT
       - name: Connect server and pull image Frontend/Backend
         env:
           PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
@@ -92,7 +96,10 @@ jobs:
           REPOSITORYAPI: ${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-api
           REPOSITORYCLIENT: ${{ secrets.DOCKERHUB_USERNAME }}/foodadvisor-client
         run: |
-          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
+          echo "$PRIVATE_KEY" > private_key 
+          echo "chmod 600 private_key"
+          echo "SSH User: ${{secrets.SSH_USER }}"
+          echo "EC2 Instance DNS: ${{ env.INSTANCE_PUBLIC_DNS }}"
           ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.SSH_USER }}@${{ env.INSTANCE_PUBLIC_DNS }} << EOF
           sudo yum install -y docker
           sudo systemctl start docker
@@ -107,12 +114,30 @@ jobs:
             -e STRAPI_ADMIN_CLIENT_PREVIEW_SECRET=${{ secrets.JWT_SECRET }} \
             $REPOSITORYAPI:latest
 
+          echo "Checking API Container Status..."
+          API_STATUS=$(sudo docker inspect -f '{{.State.Status}}' foodadvisor-api)
+          if [ "$API_STATUS" != "running" ]; then
+            echo "API container failed to start. Check logs for details."
+            sudo docker logs foodadvisor-api
+            exit 1
+          fi
+          echo "foodadvisor-api deployed successfully."
+
           echo "Deploying Client"
           sudo docker pull $REPOSITORYCLIENT:latest
           sudo docker run -d --name foodadvisor-client \
             -p 3000:3000 \
             -e NEXT_PUBLIC_API_URL=http://${INSTANCE_PUBLIC_IPV4}:1337 \
             $REPOSITORYCLIENT:latest
+
+          echo "Checking Client Container Status..."
+          CLIENT_STATUS=$(sudo docker inspect -f '{{.State.Status}}' foodadvisor-client)
+          if [ "$CLIENT_STATUS" != "running" ]; then
+            echo "API container failed to start. Check logs for details."
+            sudo docker logs foodadvisor-client
+            exit 1
+          fi
+          echo "foodadvisor-client deployed successfully."  
 
           echo "Deployed API: http://${INSTANCE_PUBLIC_IPV4}:1337/"
           echo "Deployed Client: http://${INSTANCE_PUBLIC_IPV4}:3000/"
